### ISSUE TITLE
复现时出现了梯度计算报错

### ISSUE THREAD

**Issue by Alex-seven** [thuml/Anomaly-Transformer#10]
![image](https://user-images.githubusercontent.com/35769246/170455727-93013936-e8c1-4703-8af2-ab0df1fec6bd.png)

但是，注掉loss2.backward代码可以通过

**Comment by wuhaixu2016** [comment]
We have claimed this clearly in the readme.
Pytorch version should be 1.4.0.

**Comment by Alex-seven** [comment]
> We have claimed this clearly in the readme. Pytorch version should be 1.4.0.

解决了，感谢
