### ISSUE TITLE
关于SMAP数据集

### ISSUE THREAD

**Issue by kanesp** [thuml/Anomaly-Transformer#13]
你好，在提供的清华镜像SMAP里面没找到SMAP_test_label.npy这个标签数据，方便提供一下吗？感谢。

`FileNotFoundError: [Errno 2] No such file or directory: 'dataset/SMAP/SMAP_test_label.npy'
`

**Comment by wuhaixu2016** [comment]
Yes, we have updated the cloud link. You can download that now.

**Comment by kanesp** [comment]
非常感谢！已引用这篇工作。Thank you very much. We have cited this manuscript. It is helpful. :)
