### ISSUE TITLE
关于 UCR 数据集

### ISSUE THREAD

**Issue by ForestsKing** [thuml/Anomaly-Transformer#16]
您好，在KDD2021 Multi-dataset Time Series Anomaly Detection的网站里我未能找到标注文件。方便提供一下吗？感谢。

**Comment by wuhaixu2016** [comment]
您好，我们就是在KDD cup官网上下载了，您可以重新check一下

**Comment by ForestsKing** [comment]
好的，我在讨论区找到了链接，谢谢

**Comment by tribeband** [comment]
能放上来吗？

**Comment by BlackiePiggy** [comment]
不知道是否正确，在这里贴一下：
https://www.cs.ucr.edu/~eamonn/time_series_data_2018/UCR_TimeSeriesAnomalyDatasets2021.zip
