### ISSUE TITLE
关于 Minimax Strategy 的顺序

### ISSUE THREAD

**Issue by ForestsKing** [thuml/Anomaly-Transformer#17]
关于Minimax Strategy ，我理解的您论文中的表述是需要先 minimize 使 P 靠近 S，再 maximize 使 S 远离 P。但是注意到您代码中似乎是先 maximize 再 minimize。想请问下 Minimax Strategy 的顺序对模型训练有影响吗？谢谢！
```
loss1 = rec_loss - self.k * series_loss
loss2 = rec_loss + self.k * prior_loss

loss1.backward(retain_graph=True)
loss2.backward()
```

**Comment by wuhaixu2016** [comment]
这个对于最终结果没有影响，您也可以替换两者
