### ISSUE TITLE
关于 UCR 数据集的使用

### ISSUE THREAD

**Issue by ForestsKing** [thuml/Anomaly-Transformer#20]
据我所知，UCR数据集由250个不由的子数据集组成，每个子数据集仅有一个时间段异常。想请教下您是采用什么策略进行模型测试的？是从250个子数据集中抽取了几个吗？

**Comment by wuhaixu2016** [comment]
我们在250个子数据集选取一些作为训练，另外一部分作为测试。具体拆分方法我们会尽快更新至本repo

**Comment by leilichuan** [comment]
Hello, could you please provide the preprocessing script of UCR dataset? The UCR dataset consists of multiple categories of sensor data. I think the UCR dataset should also be trained and evaluated separately according to the category(sensor) of data just like you train all the machines together in SMD datasets

**Comment by BlackiePiggy** [comment]
> 我们在250个子数据集选取一些作为训练，另外一部分作为测试。具体拆分方法我们会尽快更新至本repo

请问这个工作大概什么时候能发布出来。现在所有提供的数据集都是多维数据，可视化与可解释性分析较难进行。希望能提供UCR或其他一维数据的数据集制作方法。
