### ISSUE TITLE
About NeurIPS-TS dataset

### ISSUE THREAD

**Issue by DRMBSGN** [thuml/Anomaly-Transformer#23]
I want to know the details about what you experimented using NeurIPS-TS dataset.
According to the paper, It includes univariate time series which have total length of 50,000.
I couldn't find any information about  how to generate or sample that train, test samples.
Could you explain more detailed design of your experiment using this dataset?  Is there any future plans to update the related codes?

**Comment by wuhaixu2016** [comment]
You can find the corresponding citation from our paper [1]. 
[1] Kwei-Herng Lai, D. Zha, Junjie Xu, and Yue Zhao. Revisiting time series outlier detection: Deﬁnitions and benchmarks. In NeurIPS Dataset and Benchmark Track, 2021.
Especially, the generation code is here: https://github.com/datamllab/tods/tree/benchmark/benchmark
