### ISSUE TITLE
关于数据集的疑惑

### ISSUE THREAD

**Issue by willionZS** [thuml/Anomaly-Transformer#28]
您好，我正在使用这个论文的数据集去评测其它模型。有一个疑问，这里的训练集是否有包含异常段。
我常规的做法是，训练阶段，模型只从正常数据里学习，预测阶段，当重建的LOSS比较大的时候，根据阈值判定异常段。不知道这里的数据集是否和我的常规做法相同。感谢

**Comment by wuhaixu2016** [comment]
是存在异常段的。请看论文数据集介绍。
因为是无监督学习，训练数据集如果有全是正常的前提要求，那就不能称为完全的无监督学习了吧。

**Comment by willionZS** [comment]
感谢告知，谢谢啦

**Comment by tribeband** [comment]
数据集里有异常端还叫无监督吗？
