### ISSUE TITLE
在测试SMD的时候step为什么会设置成100呢？

### ISSUE THREAD

**Issue by LIUHAO121** [thuml/Anomaly-Transformer#29]
https://github.com/thuml/Anomaly-Transformer/blob/main/data_factory/data_loader.py#L204
为什么smd为100，其他数据集都是1，论文里也没有详细的说明

**Comment by wuhaixu2016** [comment]
SMD不是连续的series，如果不设置为100，会存在不同的series被拼接在一起的情况。
