### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by Naji-Najari** [thuml/Anomaly-Transformer#3]
Hello, 
When I run bash ./scripts/MSL.sh, I get the following error:
` Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512, 55]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.
You can try pytorch 1.4.0. It works well in this environment.

**Comment by Naji-Najari** [comment]
Than you for your reply. 
But, I got the same error with pytorch 1.4.0 !
