### ISSUE TITLE
Some issues about baseline and SOTA methods

### ISSUE THREAD

**Issue by yyysjz1997** [thuml/Anomaly-Transformer#33]
Many thanks for your excellent work! 

I would like to know about the details of the baselines and SOTA method codes. I can not find any official code for the **LSTM, LSTM-VAE, BeatGAN, and THOC** methods. Can you provide some links and code repo for us to reproduce?

Thanks again! Look forward to your kind reply!!

**Comment by Jiehui-Xu** [comment]
Thank you for your interest in our work.

Some of the baselines you mentioned  is not officially open source yet. We reproduced their code as described in the authors' paper. You can contact the authors by email if you are unsure of anything during the process of reproducing the code.
