### ISSUE TITLE
请问在训练的时候为什么使用 "index:index + self.win_size" 来准备数据集？

### ISSUE THREAD

**Issue by runningJ** [thuml/Anomaly-Transformer#40]
在实际应用场景中，为了考虑报警的实时性，没办法取到当前时刻点之后的100个窗口的数据，请问是我理解的有偏差吗？

**Comment by Jiehui-Xu** [comment]
窗口的长度可以自行调整，选择100只是为了保持一个一致的实验设定。

**Comment by lllyt8** [comment]
窗口的步长也可以自行调整，如果希望更加精细可以设置step=1。
