### ISSUE TITLE
关于评价指标的计算问题

### ISSUE THREAD

**Issue by mojin2855** [thuml/Anomaly-Transformer#43]
`        # detection adjustment
        anomaly_state = False
        for i in range(len(gt)):
            if gt[i] == 1 and pred[i] == 1 and not anomaly_state:
                anomaly_state = True
                for j in range(i, 0, -1):
                    if gt[j] == 0:
                        break
                    else:
                        if pred[j] == 0:
                            pred[j] = 1
                for j in range(i, len(gt)):
                    if gt[j] == 0:
                        break
                    else:
                        if pred[j] == 0:
                            pred[j] = 1
            elif gt[i] == 0:
                anomaly_state = False
            if anomaly_state:
                pred[i] = 1`
求教这段代码目的是根据测试集标签将模型测试结果进行修正吗？
如果是的话在测试集没有标签时（实际应用中测试集本来就是没有标签的）模型不就失效了吗？

**Comment by wuhaixu2016** [comment]
您好，请见https://github.com/thuml/Anomaly-Transformer/issues/14
我们在readme中也有提及

**Comment by aesdhj** [comment]
看了一圈，作者都没直接回答问题，1，真实数据没有label,adjust这段代码怎么办？2，为什么adjust注释掉以后，性能大幅下降？

**Comment by xiaobiao998** [comment]
想请教一下，如何解决没有测试集标签的问题了，谢谢

**Comment by xiaobiao998** [comment]
> 看了一圈，作者都没直接回答问题，1，真实数据没有label,adjust这段代码怎么办？2，为什么adjust注释掉以后，性能大幅下降？

请问这个问题解决了嘛，有什么方法可以克服没有测试标签的问题嘛，谢谢
