### ISSUE TITLE
bugs happens when doing the backward propgation for loss1 and loss2 in train function 

### ISSUE THREAD

**Issue by RudolphXu** [thuml/Anomaly-Transformer#5]
Really exccllent work!
Just met a RuntimeError when the program went to line 191 in solver.py
It is saying that

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512, 55]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

I am running in  Python3.8 and pytorch 1.6.0.
Not sure whether it is a compatibility issue.

Thank you!

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.

We specifically clarify this. **The Pytorch version should be 1.4.0**. You can change the pytorch version and try again.
