### ISSUE TITLE
Some results inconsistent with the original paper of other methods

### ISSUE THREAD

**Issue by Conearth** [thuml/Anomaly-Transformer#6]
Hi ! Thx for your attention.
In your paper, I found some results inconsistent with the original paper of other methods, like "OmniAnomaly" and "InterFusion". Is there some thing different in experiment detail?

**Comment by wuhaixu2016** [comment]
Hi, this mismatch is because of the inconsistency in the dataset. For example, in SMD, we adopt the full dataset, while other methods use only part of the dataset.
I think you can obtain the standard benchmark in this repo.

**Comment by Conearth** [comment]
Yeah, this makes sense. I also noticed that other methods like 'interfusion', they seems do training and evaluation once in a single entity(for SMD, i.e. machin-x-x.), while your experiments train and evaluate the model on the whole dataset. Is this the cause of the inconsistency with the original 'interfusion' 'OmniAnomoly' papers？Thank you very much.

**Comment by wuhaixu2016** [comment]
Yes, you can check the data source for the data splitting strategy.

**Comment by Conearth** [comment]
Many thx.
