### ISSUE TITLE
loss和criterion问题

### ISSUE THREAD

**Issue by LiYunxiaoboy** [thuml/Anomaly-Transformer#60]
我发现在loss计算时，单独使用重建损失作为优化目标。使用您文章中所提到的Assoc作为异常域阀确定，所算出的评价指标和文中的几乎没有变化，请问这是否说明，文中提出的关联差异不是很有效；而是Assoc起到了至关作用，但很明显并没有使用关联差异作为优化目标，请问为什么会出现这种情况呢？

**Comment by lzz19980125** [comment]
计算loss的过程中在使用重建损失的同时还使用了Assoc，并且采用MinMax方法进行训练，Assoc肯定是起作用了
