### ISSUE TITLE
About the Gaussian Kernel as used in the paper

### ISSUE THREAD

**Issue by luisfredgs** [thuml/Anomaly-Transformer#61]
Hello,
Thanks for sharing your study with us. I have noted the Gaussian kernel as used in the code uses `2 / (sigma ** 2)` instead  `2 * (sigma ** 2)`. Why?

Refer to: https://github.com/thuml/Anomaly-Transformer/blob/b0ee470c8012bff857fb600462aec6209c4a18d9/model/attn.py#L52

**Comment by ghost** [comment]
I guess -prior ** 2 / 2 / (sigma ** 2)==-prior ** 2 / (2 * (sigma ** 2)) ?

**Comment by luisfredgs** [comment]
> I guess -prior ** 2 / 2 / (sigma ** 2)==-prior ** 2 / (2 * (sigma ** 2)) ?

Yes.
