### ISSUE TITLE
运行时卡在模型实例化

### ISSUE THREAD

**Issue by hhhercules** [thuml/Anomaly-Transformer#7]
运行时会在实例化solver卡住，具体是在 self.build_model() -> self.model = AnomalyTransformer(win_size=self.win_size, enc_in=self.input_c, c_out=self.output_c, e_layers=3) -> self.encoder = Encoder(...) 
并没有报错，只是运行到这里时就卡住了,不知道是什么原因导致的？
python 3.6, cuda 10.1, pytorch 1.4.0 GPU型号A100

**Comment by wuhaixu2016** [comment]
我们论文的实验环境是3090。
这个情况我没有遇到过，不过我觉得可能是因为你的cuda版本和GPU型号不匹配，您再可以找找其他资料。

**Comment by Hymnhyz** [comment]
> 运行时会在实例化solver卡住，具体是在 self.build_model() -> self.model = AnomalyTransformer(win_size=self.win_size, enc_in=self.input_c, c_out=self.output_c, e_layers=3) -> self.encoder = Encoder(...) 并没有报错，只是运行到这里时就卡住了,不知道是什么原因导致的？ python 3.6, cuda 10.1, pytorch 1.4.0 GPU型号A100

这个问题是因为 30系显卡需要 cuda 11   你使用 .cuda() 就会卡住  所以需要升级cuda 版本就好了
